### ISSUE TITLE
start_point vs starting_point

### ISSUE THREAD

**Issue by mabushey** [aabiji/muse#6]
The last line in the readme config is:
`starting_point = 0`

When I run `muse play`, I get
```
TOML parse error at line 1, column 1
  |
1 | # A list of directory paths that 
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
missing field `start_point`
```

when I remove the `ing`, I now get:
```
muse play       
thread 'main' panicked at src/audio.rs:113:34:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/net.rs:47:44:
called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mabushey** [comment]
```
RUST_BACKTRACE=1 muse play
thread 'main' panicked at src/audio.rs:113:34:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:127:5
   3: muse::audio::Playback::read_tracks
   4: muse::audio::Playback::play
   5: muse::net::Server::run
   6: muse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at src/net.rs:47:44:
called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
   3: muse::net::read_data
   4: muse::net::Client::run
   5: muse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
